# -----------------------
# Build Angular
# -----------------------
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# -----------------------
# Serve with Nginx
# -----------------------
FROM nginx:alpine

# Copiar build de Angular al html de Nginx
COPY --from=build /app/dist/findex-frontend /usr/share/nginx/html

# Configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
